version: '2.3'
services:
    ftpd:
        image: 'stilliard/pure-ftpd'
        container_name: 'ftpd'
        ports:
            - '21:21'
            - '30000-30009:30000-30009'
        volumes:
            - /data/ftp:/home/ftpusers/
            - /etc/pure-ftpd/passwd:/etc/pure-ftpd/passwd
            - /etc/ssl/private/:/etc/ssl/private/
        environment:
            PUBLICHOST: 'localhost'
