version: '2.3'
services:
    grafana:
        image: 'grafana/grafana:latest'
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - ~/Docker/grafana:/var/lib/grafana
            - ~/Docker/etc/grafana:/etc/grafana
        environment:
            GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
            GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
        restart: always
        hostname: grafana
        cpus: 0.5
        mem_limit: 2048M
    influxdb:
        image: 'influxdb:latest'
        container_name: influxdb
        ports:
            - 8086:8086
        volumes:
            - ~/Docker/etc/influxdb.conf:/etc/influxdb/influxdb.conf
            - ~/Docker/influxdb:/var/lib/influxdb
        environment:
            INFLUXDB_DB: db0
            INFLUXDB_ADMIN_USER: $INFLUXDB_ADMIN_USER
            INFLUXDB_ADMIN_PASSWORD: $INFLUXDB_ADMIN_PASSWORD
            INFLUXDB_READ_USER: grafana
            INFLUXDB_READ_USER_PASSWORD: $INFLUXDB_USER_PASSWORD
        restart: always
        hostname: influxdb
        cpus: 0.5
        mem_limit: 2048M