version: '2.3'
services:
    grafana:
        image: 'grafana/grafana:latest'
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - ~/Docker/grafana:/var/lib/grafana
            - ~/Docker/etc/grafana:/etc/grafana
        environment:
            GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
            GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
        restart: always
        hostname: grafana
        cpus: 0.5
        mem_limit: 2048M