version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MGMT_PORT:-15672}:15672
    volumes:
      - ${RABBITMQ_DATA_DIR:-/data/rabbitmq}:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_ROOT_USERNAME:-root}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ROOT_PASSWORD:?error}
