version: '2.3'
services:
    grafana:
        image: 'gitlab/gitlab-ce:latest'
        container_name: gitlab
        ports:
            - '22:22'
            - '80:80'
            - '443:443'
        volumes:
            - /data/gitlab/config:/etc/gitlab
            - /data/gitlab/logs:/var/log/gitlab
            - /data/gitlab/data:/var/opt/gitlab
        restart: always
        hostname: gitlab
