version: '2.3'
services:
    sentry:
        environment:
            SENTRY_SECRET_KEY: $SENTRY_SECRET_KEY
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_POSTGRES_PORT: 5432
            SENTRY_DB_NAME: sentry
            SENTRY_DB_USER: sentry
            SENTRY_DB_PASSWORD: $SENTRY_DB_PASSWORD
            SENTRY_REDIS_HOST: redis
            SENTRY_SERVER_EMAIL: $SENTRY_SERVER_EMAIL
            SENTRY_EMAIL_HOST: $SENTRY_EMAIL_HOST
            SENTRY_EMAIL_PORT: $SENTRY_EMAIL_PORT
            SENTRY_EMAIL_USER: $SENTRY_EMAIL_USER
            SENTRY_EMAIL_PASSWORD: $SENTRY_EMAIL_PASSWORD
        cpus: 0.2
        mem_limit: 512M