version: '2.3'
services:
    sentry:
        image: 'sentry:8.20'
        container_name: sentry
        depends_on:
            - redis
            - postgres
        links:
            - postgres
            - redis
        ports:
            - 9000:9000
        cpus: 0.25
        mem_limit: 2048M
        networks:
            sentry:
                ipv4_address: 172.16.4.10
        extends:
            file: base.yml
            service: sentry
    sentry-cron:
        image: 'sentry:8.20'
        container_name: sentry-cron
        command: sentry run cron
        depends_on:
            - sentry
        links:
            - postgres
            - redis
        cpus: 0.2
        mem_limit: 512M
        networks:
            sentry:
                ipv4_address: 172.16.4.11
        extends:
            file: base.yml
            service: sentry
    sentry-worker-1:
        image: 'sentry:8.20'
        container_name: sentry-worker-1
        command: sentry run worker
        depends_on:
            - sentry
        links:
            - postgres
            - redis
        cpus: 0.2
        mem_limit: 512M
        networks:
            sentry:
                ipv4_address: 172.16.4.12
        extends:
            file: base.yml
            service: sentry

    redis:
        image: 'redis:latest'
        container_name: sentry-redis
        restart: on-failure
        cpus: 0.2
        mem_limit: 512M
        networks:
            sentry:
                ipv4_address: 172.16.4.20

    postgres:
        image: 'postgres:latest'
        container_name: sentry-postgres
        cpus: 0.25
        mem_limit: 1024M
        environment:
            POSTGRES_USER: sentry
            POSTGRES_PASSWORD: AeshaphiWood7she
        volumes:
            - /data/psql:/var/lib/postgresql/data
        networks:
            sentry:
                ipv4_address: 172.16.4.21

networks:
    sentry:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: 172.16.4.0/24
                    gateway: 172.16.4.1