version: '2.3'
services:
    l2tp:
        image: 'hwdsl2/ipsec-vpn-server'
        container_name: l2tp
        ports:
            - 500:500/udp
            - 4500:4500/udp
        volumes:
            - /lib/modules:/lib/modules:ro
        environment:
            VPN_IPSEC_PSK: $VPN_IPSEC_PSK
            VPN_USER: $VPN_USER
            VPN_PASSWORD: $VPN_PASSWORD
        restart: always
        hostname: l2tp
        privileged: true