version: '2.3'
services:
    mysql:
        image: 'mysql:latest'
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ~/Docker/mysql:/var/lib/mysql
            - ~/Docker/etc/mysql:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        restart: always
        hostname: mongo
        cpus: 0.5
        mem_limit: 2048M