version: "3"
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ${POSTGRES_DATA_DIR:-/data/postgres}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-3306}
